### ISSUE TITLE
[feature] Provide a simple Dockerfile and auto-publish to DockerHub

### ISSUE THREAD

**Issue by AndreMiras** [TheKevJames/coveralls-python#246]
The idea is to create a simple Dockerfile (I can help with that) e.g. in the root directory if this repo then setup DockerHub to automatically pick it up.
Here's a bit of context why we may want that.
I'm providing a GitHub action (https://github.com/AndreMiras/coveralls-python-action) that relies on this `coveralls` package.
In order make this GitHub Action available I need to build a Docker container that simply `pip install coveralls`, see:
https://github.com/AndreMiras/coveralls-python-action/blob/v20201129/Dockerfile
Whenever a user uses this action the Docker container will be built. In the state of the `Dockerfile` shared above it takes ~30 seconds (pulling the Python base image and running the `pip install coveralls`).
Recently I got a question from an user about the build time https://github.com/AndreMiras/coveralls-python-action/issues/9 therefore I've implemented a fix consisting in publishing a prebuilt coveralls image to DockerHub which helped speeding up the whole action setup time down from ~30 seconds to ~15 seconds, see https://github.com/AndreMiras/coveralls-python-action/commit/501c024a4e8997d48fe41fc076ce7b87921c1f48.
The prebuilt image is pretty simple see ~https://github.com/AndreMiras/coveralls-python-action~ https://github.com/AndreMiras/docker-coveralls
Then setting up automated built on DockerHub is very simple too.
While this is working completely fine, I thought it would be better if the official coveralls-python maintainers were providing this Docker image rather than a random dude :smile: 

If we decide to implement this task, a follow up task could be providing different images for different Python base. But for now having simply one `Dockerfile` from e.g. `python:3.8-slim` should be more than enough

**Comment by TheKevJames** [comment]
Providing a pre-built docker container makes sense to me!

For my personal CI stuff, I tend to prefer minimal-as-possible images, as they are fastest to work with (see some of the [other OSS images I maintain](https://github.com/thekevjames/tools) for what I mean); ie. alpine, minimal additional things installed, etc. I'd probably default to something like: "from python:alpine, install git, install pre-commit"

Have you found users needing anything besides access to the `coveralls` command (and `git`, for linking to the repo)?

**Comment by AndreMiras** [comment]
Thanks for getting back.
Yeah I think keeping it minimal should be good, I haven't seen other needs than `coveralls` and `git` so far indeed.
I realised I didn't properly link the temporary prebuilt image I've made. Here it is: https://github.com/AndreMiras/docker-coveralls/blob/dc056ce/Dockerfile and indeed it's as simple as you suggested:
```
FROM python:3.8-slim

RUN apt update -qq > /dev/null && apt install -qq --yes --no-install-recommends \
    git \
    && pip install coveralls
```

**Comment by TheKevJames** [comment]
@AndreMiras done! The image will now autobuild to `thekevjames/coveralls` ([ref: dockerhub](https://hub.docker.com/repository/docker/thekevjames/coveralls/general)). I'm just backfilling the versioned builds now (eg. so you can pin to `thekevjames/coveralls:2.2.0`, for example) -- those should be live shortly. Please let me know if you run into any issues with the images!

**Comment by AndreMiras** [comment]
Nice thanks, I've switched to it now and everything looks OK so far.
Maybe you could add the Docker badge to the project README.md
```
[![Docker Build](https://img.shields.io/docker/cloud/build/thekevjames/coveralls)](https://hub.docker.com/r/thekevjames/coveralls)
```

**Comment by TheKevJames** [comment]
Another great suggestion -- done!
