### ISSUE TITLE
Using coveralls with arbitrary CI service

### ISSUE THREAD

**Issue by Silmathoron** [TheKevJames/coveralls-python#256]
Would it be possible to add a explanation in the docs on how to use coverall with arbitrary CI?
As far as I understood from previous discussions, even if I run a test on my laptop, I should be able to send it to coveralls.io.

Ideally, I'd like to find an example showing:
1. how to to this using only ``.coveralls.yml``
2. how to do it using only environment variables.

I tried using the [Azure workaround](https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#azure-pipelines-support) from the docs to use coveralls with SourceHut as a CI to no avail.

What I was using so far was a ``.coveralls.yml`` file containing:

    service_name: sourcehut
    repo_token: my-token

and the command ``CIRCLECI=1 CIRCLE_BRANCH=master CIRCLE_BUILD_NUM=$JOB_ID coveralls``.

This leads to the following error with coverals 3.0

    Submitting coverage to coveralls.io...
    resubmitting with id 394610-3497017197683832333
    Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
    Traceback (most recent call last):
      File "/home/build/.local/lib/python3.8/site-packages/coveralls/api.py", line 252, in wear
        response.raise_for_status()
      File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
        raise HTTPError(http_error_msg, response=self)
    requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/build/.local/lib/python3.8/site-packages/coveralls/cli.py", line 85, in main
        result = coverallz.wear()
      File "/home/build/.local/lib/python3.8/site-packages/coveralls/api.py", line 255, in wear
        raise CoverallsException('Could not submit coverage: {}'.format(e))
    coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

Running it in debug mode runs fine: ``CIRCLECI=1 CIRCLE_BRANCH=master CIRCLE_BUILD_NUM=$JOB_ID coveralls debug`` gives the following [log](https://yui.runners.sr.ht/logs/394625/test/log).

**Comment by TheKevJames** [comment]
@Silmathoron with the linked PR (#300), this flow should now be much more clear -- please let me know if this works for you with the latest version! You can find the docs [here](https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html#other-ci-systems)

**Comment by Silmathoron** [comment]
Yep, working fine now, thanks a lot!
