### ISSUE TITLE
Difficult to find documentation on where coveragerc file is supposed to go

### ISSUE THREAD

**Issue by ahill187** [TheKevJames/coveralls-python#270]
On the configuration documentation found here: https://coveralls-python.readthedocs.io/en/latest/usage/configuration.html
it says:

> If you have placed your .coveragerc in a non-standard location, you can run:
> ```coveralls --rcfile=/path/to/coveragerc```

It is not clear what is meant by a "non-standard location," or what the standard location should be?

**Comment by TheKevJames** [comment]
Hi @ahill187 -- thanks for the heads up on this! The default location is `./.coveragerc`, eg. in the same folder as you run `coveralls`. I've [updated the docs](https://github.com/TheKevJames/coveralls-python/commit/2829e4ed709c950422d7cefb159e56d95f7829d4) accordingly to make it a bit clearer.
