### ISSUE TITLE
Add option to specify a 'base path' for source files to support monorepos

### ISSUE THREAD

**Issue by RaddishIoW** [TheKevJames/coveralls-python#272]
I have a monorepo with several projects in a format similar to:
```
/
  /project-one
  /project-two
  ...etc
```
and I'd like to have that layout reflected in my coveralls reports.

The [Coveralls Github Action](https://github.com/marketplace/actions/coveralls-github-action) allows this through a flag called `base-path`.

Could I add this to coveralls-python through a PR?

I can see that the Coveralls Github Action does this by prepending the file paths in the source files listed in the coverage report before uploading.
Having a quick look at the code, I think this can be done relatively easily, but wonder if it would be best to do this in `api.Coveralls.create_data()` before merging any `extra` or after that? Is that the right place to be modifying the source file paths?

Let me know what you think?
Thanks!

**Comment by TheKevJames** [comment]
Hi @RaddishIoW -- I've just merged #306 which should help unblock this by allowing you to provide the `--srcdir=project-one` path. Please let me know if this works for you!

If there's anything else you need to support on this one, please feel free to comment back here or open a PR.

**Comment by RaddishIoW** [comment]
@TheKevJames Thanks for that - I'll take a look when I get a chance! :)
