### ISSUE TITLE
Uploading kcov output to coveralls.io results in 0% coverage

### ISSUE THREAD

**Issue by dinko-pehar** [TheKevJames/coveralls-python#301]
Output of `coveralls --service=github debug`:
```

Missing .coveralls.yml file. Using only env variables.
Testing coveralls-python...
{"source_files": [], "git": {"branch": "extra-branch", "head": {"id": "7033f4e955cf6ed278372a093cb2887094f6e229", "author_name": "Dinko Pehar", "author_email": "dinko.pehar@reduced.com", "committer_name": "Dinko Pehar", "committer_email": "dinko.pehar@reduced.com", "message": "Final"}, "remotes": [{"name": "origin", "url": "git@github.com:pentest115/stumpy_png.git"}]}, "service_name": "github", "config_file": ".coveragerc", "base_dir": ""}
==
Reporting 0 files
==

```

Hello.

I'm trying to find a way to upload coverage data to coveralls.io . Currently, what I do, is build a binary for Crystal lang and use `kcov` coverage tool to generate coverage report.

```
   ϗ kcov --clean --include-path=$(pwd)/src $(pwd)/coverage ./specs                         [7033f4e] 
Run options: --seed 14170 --parallel 1

..........

Finished in 00:00:00.012737299, 78.50958040633262 runs/s

10 tests, 0 failures, 0 errors, 0 skips
```

[coverage.zip](https://github.com/TheKevJames/coveralls-python/files/6618417/coverage.zip)

I uploaded a zip file which you can browse covered code.

---

I'm having difficulties uploading to coveralls.io using `coveralls` command. It states that there is 0% coverage, but from `kcov` output we see that is not the case.

Can you help me resolve this one ?

**Comment by TheKevJames** [comment]
Hi @dinko-pehar -- I'm not personally familiar with the `kcov` command (or the Crystal language in general!), but you can find the instructions for integrating other tools in our docs [here](https://coveralls-python.readthedocs.io/en/latest/usage/multilang.html).

The general rule is to have the external tools (eg. `kcov` here) produce a JSON file which can then by merged in to the `coveralls` results via: `coveralls --merge=my-coverage.json`.

**Comment by dinko-pehar** [comment]
Unfortunately, reports created by `kcov` can't be uploaded to coveralls.io . `kcov` is a great tool and it generates many reports, but coveralls.io only supports lcov reports. I didn't managed to convert any format to lcov. So I switched to codecov.io . You can close issue if you want.

**Comment by TheKevJames** [comment]
Ah, sorry to hear that. It looks like it might be possible to convert from kcov to lcov data, but I wasn't able to find an existing project to handle that case; looks like something that would need to be built explicitly to handle this case.

Thanks for the report either way, I'll clean up our docs accordingly to make sure it's called out that we can only support lcov data at this time.
