### ISSUE TITLE
Support for coverage 6

### ISSUE THREAD

**Issue by McSinyx** [TheKevJames/coveralls-python#320]
Hi, coverage 6.0b1 was released last month, could you investigate if coveralls is compatible with it and relax the runtime requirement sometime in the future?

**Comment by purificant** [comment]
It would be good to support coverage 6.0

**Comment by TheKevJames** [comment]
Now solved in v3.3.0! Thanks to @arcivanov for the PR submission :)

**Comment by arcivanov** [comment]
Thanks, @TheKevJames!

**Comment by purificant** [comment]
Thank you @TheKevJames, @arcivanov :pray:
