### ISSUE TITLE
ImportError: cannot import name 'Reporter' from 'coverage.report'

### ISSUE THREAD

**Issue by walter-weinmann** [TheKevJames/coveralls-python#341]
![image](https://user-images.githubusercontent.com/1956149/151517656-eb2b56f6-f796-4a74-9f4c-df5076bea0d3.png)

**Comment by mcdonnnj** [comment]
You appear to be in the wrong repository. The [python-coveralls](https://pypi.org/project/python-coveralls/) project is housed in https://github.com/z4r/python-coveralls. This repository is for the [coveralls](https://pypi.org/project/coveralls/) project.

**Comment by walter-weinmann** [comment]
Sorry - thanks for the help anyway.
