### ISSUE TITLE
Add python-coveralls entrypoint

### ISSUE THREAD

**Issue by ericdill** [TheKevJames/coveralls-python#345]
Hey @TheKevJames -- what do you think about adding another entrypoint `python-coveralls`? We're using `cpp-coveralls` in one of our projects and that library has both the `coveralls` entrypoint as well as the `cpp-coveralls` entrypoint. If both `coveralls-python` and `cpp-coveralls` are installed together then the `coveralls` CLI is non-deterministic. One way around that would be to add an explicit `python-coveralls` (or `coveralls-python`) entrypoint to the setup.py here so that users can specifically select which coveralls CLI they want to use. Thoughts? If you approve I'm happy to submit PRs here and to the conda-forge feedstock.

https://github.com/eddyxu/cpp-coveralls/blob/master/setup.py#L47-L48

**Comment by TheKevJames** [comment]
Hi @ericdill, I would be comfortable accepting a PR which adds the `python-coveralls` entrypoint.
