### ISSUE TITLE
ModuleNotFoundError: No module named 'setuptools.command.build'

### ISSUE THREAD

**Issue by LostInDarkMath** [TheKevJames/coveralls-python#366]
Hi there! I faced this strange error in my CI: https://app.travis-ci.com/github/LostInDarkMath/pedantic-python-decorators/jobs/586586853

It fails only with Python 3.9 and 3.10. 3.7 and 3.8 are working fine:
https://github.com/LostInDarkMath/pedantic-python-decorators/pull/71/checks?check_run_id=9091764326

Do you have an idea what's wrong here? Thanks in advance!

**Comment by TheKevJames** [comment]
Should be solved with the upcoming version, as `setuptools` is no longer an explicit dependency.
