### ISSUE TITLE
Support coverage 7.0

### ISSUE THREAD

**Issue by agronholm** [TheKevJames/coveralls-python#373]
For some reason, coveralls has an upper boundary that prevents it from installing together with coverage 7.0.0. Could this restriction be removed?

**Comment by agronholm** [comment]
The reason for this request is that currently `pip install coverage[toml] coveralls` results in coveralls 1.8.0 being installed which fails due to compatibility issues.

**Comment by ya-pekatoros** [comment]
Upd. Also gain that fil when tryed to install it.

**Comment by LincolnPuzey** [comment]
To use coverage 7.0, a workaround I found was to swap from this library to the coveralls.io-maintained github action:
* https://docs.coveralls.io/integrations#official-integrations
* https://github.com/marketplace/actions/coveralls-github-action

Though I don't think the action natively supports reading from `.coverage` files, so I had to add an extra step to my CI to generate `coverage.xml` then tell the action to upload that file: https://github.com/romgar/django-dirtyfields/commit/572823e8beb98fb1dc6cda94988ec49265561a85

**Comment by agronholm** [comment]
Unfortunately that doesn't seem to work on macOS runners:
![image](https://github.com/TheKevJames/coveralls-python/assets/130003/8709f2bc-e2de-4d44-aef5-e356e0374937)
