### ISSUE TITLE
coveralls workflow fails on Python 3.5 and 3.6 with ubuntu-latest

### ISSUE THREAD

**Issue by andy-maier** [TheKevJames/coveralls-python#374]
See for example here: https://github.com/TheKevJames/coveralls-python/actions/runs/3765678072

This is caused by GitHub Actions having changed ubuntu-latest to now be Ubuntu 22.04, for which it no longer provides Python 3.5 and 3.6.

This can be fixed by specifying the use of ubuntu-20.04 for Python 3.5 and 3.6.

**Comment by andy-maier** [comment]
Fixed in PR #375

**Comment by gliptak** [comment]
could 3.5/3.6 dropped from supported?

https://www.python.org/downloads/

**Comment by andy-maier** [comment]
> could 3.5/3.6 dropped from supported?

Not as far as our projects are concerned, because we urgently need a solution for #252 and it would be great if we could get that solution also for Python 3.5 and 3.6.
