### ISSUE TITLE
coveralls 2.2.0 fails with KeyError: 'service_job_id'

### ISSUE THREAD

**Issue by andy-maier** [TheKevJames/coveralls-python#384]
Since a few days, coveralls 2.2.0 fails as follows, at least on Python 3.5 and 3.11.

We use coveralls 2.2.0 in order to avoid issue #252 , and up until recently that has worked fine.

```
Submitting coverage to coveralls.io...
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.11.3/x64/bin/coveralls", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/coveralls/cli.py", line 85, in main
    result = coverallz.wear()
             ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.3/x64/lib/python3.11/site-packages/coveralls/api.py", line 225, in wear
    self.config['service_job_id'], random.randint(0, sys.maxsize))
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'service_job_id'
```

coveralls is run in Gthub Actions without `--service=github`.

**Comment by TheKevJames** [comment]
Sorry, I don't have the bandwidth to support reports against older versions over `coveralls` unless a user wants to contribute a backportable fix. Closing this ticket.

Note that if #252 is an issue for you, there are various solutions in that thread which should work with the latest version of `coveralls`!
